name: delivery_reminder
description: Delivery Reminder

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^4.0.1
  flutter_native_timezone: ^1.0.4

  # logging / monitoring
  logger: ^0.9.4
  sentry: ^3.0.1
  sprintf: ^5.0.0

  # ui
  flutter_svg: ^0.19.1
  intl: ^0.16.1
  flutter_keyboard_visibility: ^4.0.2
  flutter_datetime_picker: ^1.5.0

  # di
  provider: ^4.3.3

  # storage
  sqflite: ^1.3.2+2

  # parsing
  xml: ^4.5.1

  # immutables
  freezed_annotation: ^0.12.0
  built_collection: ^4.3.2

  # state management
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

dev_dependencies:
  # core
  flutter_launcher_icons: ^0.8.1

  # test
  test: ^1.15.7
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

  # code generation: common
  build_runner: ^1.10.7
  # code generation: di
  injectable_generator: ^1.0.6
  # code generation: immutables
  freezed: ^0.12.7
  # code generation: state management
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - ./assets/menu.svg
    - ./assets/close.svg
    - ./assets/box.svg
  fonts:
    - family: Inter
      fonts:
        - asset: ./fonts/Inter-Bold.ttf
        - asset: ./fonts/Inter-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher-xxhdpi.png"
  adaptive_icon_background: "assets/icon/icon-bg.png"
  adaptive_icon_foreground: "assets/icon/icon.png"